UMNN: false
autoreg: false
batch_size: 5000
batchnorm: false
bins: 8
canonical: false
conditional: true
config:
  UMNN: false
  autoreg: false
  batch_size: 5000
  batchnorm: false
  bins: 8
  canonical: false
  conditional: true
  coupling_layers: 30
  dropout: 0.0
  gamma: 0.75
  lambda: 500
  limit: 100000
  lr: 0.001
  lr_schedule: false
  max_steps: 100000
  n_dim: 90
  n_mse: 10
  n_sched: 1000
  network_layers: 2
  network_nodes: 128
  perfection: 10000
  tail_bound: 10
coupling_layers: 30
dropout: 0.0
gamma: 0.75
lambda: 500
limit: 100000
lr: 0.001
lr_schedule: false
max_steps: 100000
n_dim: 90
n_mse: 10
n_sched: 1000
network_layers: 2
network_nodes: 128
perfection: 10000
tail_bound: 10
